name: Run Generator Script on Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
          persist-credentials: true

      - name: Run generator.sh
        run: ./generator.sh

      - name: Check for changes in sdk submodule
        id: check-for-changes
        run: |
          # Check if there are any changes in the sdk submodule
          git diff --exit-code sdk || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes to sdk submodule
        if: success() && (steps.check-for-changes.outputs.changed == 'true')
        run: |
          # Navigate into the sdk submodule and commit the changes
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          cd sdk
          
          git remote set-url origin git@github.com:${{ github.repository }}.git
          echo "${{ secrets.SDK_DEPLOY_KEY }}" > ~/deploy-key
          chmod 600 ~/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --add --global core.sshCommand 'ssh -i ~/deploy-key'

          git add .
          git checkout -b auto-generated-updates || "echo Branch 'auto-generated-updates' already exists"
          git commit -m "Auto-regenerated SDK"
          git push --set-upstream origin auto-generated-updates
