name: Run Generator Script on Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
          persist-credentials: true

      - name: Run generator.sh
        run: ./generator.sh

      - name: Check for changes in sdk submodule
        id: check-for-changes
        run: |
          # Check if there are any changes in the sdk submodule
          git diff --exit-code sdk || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Configure git
        if: success() && (steps.check-for-changes.outputs.changed == 'true')
        working-directory: sdk
        run: |
          # Navigate into the sdk submodule and commit the changes
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git commit -a -m "Auto-generated SDK"


      - name: Push changes
        if: success() && (steps.check-for-changes.outputs.changed == 'true')
        uses: ad-m/github-push-action@v0.8.0
        with:
          ssh: true
          github_token: ${{ secrets.SDK_DEPLOY_KEY }}
          directory: sdk
          branch: main
          repository: felixjulianheitmann/gamevault_client_sdk

      - name: update submodule
        if: success() && (steps.check-for-changes.outputs.changed == 'true')
        working-directory: 
        run: |
          git add sdk
          git commit -m "updated submodule"
          git push
